#!/usr/bin/env python3
"""v7 = v6 + 4x taller AIV phase-2 windows (one 128KB DMA per task).

Source: ds-kernel-v6.asc   Output: ds-kernel-v7.asc
"""
import sys

SRC = 'ds-kernel-v6.asc'
DST = 'ds-kernel-v7.asc'

raw = open(SRC, encoding='utf-8', newline='').read().replace('\r\n', '\n')
N = len(raw.split('\n'))
J = '\n'.join


def rep(old, new, count=1):
    global raw
    if raw.count(old) != count:
        sys.exit('count %d != %d for:\n%r' % (raw.count(old), count, old[:200]))
    raw = raw.replace(old, new)


# --------------------------------------------------- 0. panel default 16 MB
rep('#define BMM_V6_PANEL_MB 64', '#define BMM_V6_PANEL_MB 16')

# ------------------------------- 1. kernel scope: rows per AIV task
rep(J(['    const uint32_t panelBatches =',
       '        (stripCount == 1U) ? shape.b : MinU32(batchSlice, shape.b);']),
    J(['    const uint32_t panelBatches =',
       '        (stripCount == 1U) ? shape.b : MinU32(batchSlice, shape.b);',
       '    /*',
       '     * Rows per AIV phase-2 task. The C-heavy shapes are DMA command bound:',
       '     * a 16-row window issues one command per 32KB and the per-command cost',
       '     * (~0.7us fixed + transfer) dominated the kernel. A 64-row window moves',
       '     * 128KB per command, so the same bytes cost ~4x fewer commands. Needs',
       '     * mSub == 1 and kSplits == 1; otherwise the earlier 16-row shape is used',
       '     * (the split-K staging buffer is 16 rows).',
       '     */',
       '    const uint32_t aivRows =',
       '        ((stripCount > 1U) && (mSub == 1U) && (kSplits == 1U))',
       '            ? 4U * TILE_M',
       '            : TILE_M;',
       '    const uint32_t aivRowTiles4 =',
       '        (shape.m + aivRows - 1U) / aivRows;']))

# ------------------------------- 2. AIV: bigger C window + 4 max slots
rep(J(['        pipe.InitBuffer(',
       '            cWinBuf,',
       '            TILE_M * N_CHUNK * sizeof(CDtype));',
       '        pipe.InitBuffer(',
       '            cTmpBuf,',
       '            TILE_M * N_CHUNK * sizeof(CDtype));',
       '        pipe.InitBuffer(',
       '            workBuf,']),
    J(['        pipe.InitBuffer(',
       '            cWinBuf,',
       '            4U * TILE_M * N_CHUNK * sizeof(CDtype));',
       '        pipe.InitBuffer(',
       '            cTmpBuf,',
       '            TILE_M * N_CHUNK * sizeof(CDtype));',
       '        pipe.InitBuffer(',
       '            workBuf,']))
rep(J(['        pipe.InitBuffer(',
       '            redBuf,',
       '            TILE_M * sizeof(CDtype));']),
    J(['        pipe.InitBuffer(',
       '            redBuf,',
       '            4U * TILE_M * sizeof(CDtype));']))

# ------------------------------- 3. AIV: per-panel task space (64-row tasks)
rep(J(['        const uint64_t totalRedPerPanel =',
       '            (stripCount > 1U)',
       '                ? static_cast<uint64_t>(panelBatches) * rowTiles * mSub',
       '                : static_cast<uint64_t>(shape.b) * rowTiles *',
       '                      mSub * nChunksTask;']),
    J(['        const uint64_t totalRedPerPanel =',
       '            (stripCount > 1U)',
       '                ? static_cast<uint64_t>(panelBatches) * aivRowTiles4 * mSub',
       '                : static_cast<uint64_t>(shape.b) * rowTiles *',
       '                      mSub * nChunksTask;']))

# ------------------------------- 4. AIV: 64-row window decode
rep(J(['            const uint32_t mwin =',
       '                static_cast<uint32_t>(mw % rowTiles);',
       '            const uint32_t bLocal =',
       '                static_cast<uint32_t>(mw / rowTiles);']),
    J(['            const uint32_t mwin =',
       '                (stripCount > 1U)',
       '                    ? static_cast<uint32_t>(mw % aivRowTiles4)',
       '                    : static_cast<uint32_t>(mw % rowTiles);',
       '            const uint32_t bLocal =',
       '                (stripCount > 1U)',
       '                    ? static_cast<uint32_t>(mw / aivRowTiles4)',
       '                    : static_cast<uint32_t>(mw / rowTiles);']))
rep(J(['            const uint32_t rowStart =',
       '                mwin * TILE_M + msub * subM;']),
    J(['            const uint32_t rowStart =',
       '                mwin * aivRows + msub * subM;']))

# ------------- 5. AIV: the whole reduce/write region, sub-window aware
OLD = J([
    '            const uint32_t validM = MinU32(',
    '                subM, shape.m - rowStart);',
    '',
    '            Duplicate(',
    '                bestVec,',
    '                -3.402823466e38f,',
    '                TILE_M);',
    '',
    '            /*',
    '             * Fold overflow chunks into this slot:',
    '             * accumulate the elementwise max across',
    '             * every chunk congruent to `chunk`.',
    '             */',
    '            for (uint32_t c = chunk;',
    '                 c < realChunks;',
    '                 c += nChunksTask) {',
    '                const uint32_t nStart = c * chunkW;',
    '                const uint32_t validN = MinU32(',
    '                    chunkW, shape.n - nStart);',
    '',
    '                /*',
    '                 * Stage the validM x validN window',
    '                 * in one 2D copy. When validN is a',
    '                 * multiple of 64, rows pack at the',
    '                 * validN pitch so the whole tile is',
    '                 * one contiguous stream: a single',
    '                 * vcmax batch then reduces every',
    '                 * 64-elem window, and a second call',
    '                 * folds each row\'s partials.',
    '                 */',
    '                constexpr uint32_t cElemsBlk =',
    '                    32U / sizeof(CDtype);',
    '                const uint32_t rowPitch =',
    '                    ((validN & 63U) == 0 && validN > 64)',
    '                        ? validN',
    '                        : chunkW;',
    '                DataCopyParams cp;',
    '                cp.blockCount =',
    '                    static_cast<uint16_t>(validM);'])
NEW = J([
    '            const uint32_t validM = MinU32(',
    '                subM, shape.m - rowStart);',
    '            /*',
    '             * v7: this task owns `rowsHere` rows (rowsHere/TILE_M partial',
    '             * slots) and fetches all of them with one 2D DMA, so the C-heavy',
    '             * shapes pay one command per 128KB instead of one per 32KB. Each',
    '             * 16-row sub-window is reduced and written exactly as before.',
    '             */',
    '            const uint32_t rowsHere =',
    '                MinU32(aivRows, shape.m - rowStart);',
    '            const uint32_t subWins =',
    '                (rowsHere + TILE_M - 1U) / TILE_M;',
    '            const uint32_t dmaRows =',
    '                (aivRows > TILE_M) ? rowsHere : validM;',
    '',
    '            Duplicate(',
    '                bestVec,',
    '                -3.402823466e38f,',
    '                4U * TILE_M);',
    '',
    '            /*',
    '             * Fold overflow chunks into this slot:',
    '             * accumulate the elementwise max across',
    '             * every chunk congruent to `chunk`.',
    '             */',
    '            for (uint32_t c = chunk;',
    '                 c < realChunks;',
    '                 c += nChunksTask) {',
    '                const uint32_t nStart = c * chunkW;',
    '                const uint32_t validN = MinU32(',
    '                    chunkW, shape.n - nStart);',
    '',
    '                /*',
    '                 * Stage the dmaRows x validN window',
    '                 * in one 2D copy. When validN is a',
    '                 * multiple of 64, rows pack at the',
    '                 * validN pitch so the whole tile is',
    '                 * one contiguous stream: a single',
    '                 * vcmax batch then reduces every',
    '                 * 64-elem window, and a second call',
    '                 * folds each row\'s partials.',
    '                 */',
    '                constexpr uint32_t cElemsBlk =',
    '                    32U / sizeof(CDtype);',
    '                const uint32_t rowPitch =',
    '                    ((validN & 63U) == 0 && validN > 64)',
    '                        ? validN',
    '                        : chunkW;',
    '                DataCopyParams cp;',
    '                cp.blockCount =',
    '                    static_cast<uint16_t>(dmaRows);'])
rep(OLD, NEW)

# per-row fallbacks and the split-K adds use dmaRows as well
rep(J(['                    for (uint32_t r = 0; r < validM;',
       '                         ++r) {',
       '                        DataCopyPad(',
       '                            cUb[r * rowPitch],']),
    J(['                    for (uint32_t r = 0; r < dmaRows;',
       '                         ++r) {',
       '                        DataCopyPad(',
       '                            cUb[r * rowPitch],']))
rep(J(['                        for (uint32_t r = 0;',
       '                             r < validM; ++r) {',
       '                            DataCopyPad(',
       '                                cTmpUb[r * rowPitch],']),
    J(['                        for (uint32_t r = 0;',
       '                             r < dmaRows; ++r) {',
       '                            DataCopyPad(',
       '                                cTmpUb[r * rowPitch],']))
rep(J(['                    Add(',
       '                        cUb,',
       '                        cUb,',
       '                        cTmpUb,',
       '                        validM * rowPitch);']),
    J(['                    Add(',
       '                        cUb,',
       '                        cUb,',
       '                        cTmpUb,',
       '                        dmaRows * rowPitch);']))

# ------- the reduce + write, now per sub-window, reading cUb at the right offset
rep(J([
    '                Duplicate(',
    '                    tileMaxVec,',
    '                    -3.402823466e38f,',
    '                    TILE_M);',
    '',
    '                if (rowPitch == validN) {',
    '                    /*',
    '                     * Contiguous rows: one vcmax pass',
    '                     * over validM*wRow windows (mask=64)',
    '                     * lands partials on an 8-elem pitch',
    '                     * (dstRepStride=8); gaps pre-filled',
    '                     * with -inf so a second pass can',
    '                     * fold each row\'s wRow*8-elem group',
    '                     * contiguously. wRow<=8 keeps both',
    '                     * masks under the 64-elem limit.',
    '                     */',
    '                    const uint32_t wRow = validN >> 6;',
    '                    const uint32_t nPartial =',
    '                        validM * wRow;',
    '                    Duplicate(',
    '                        reduceWork,',
    '                        -3.402823466e38f,',
    '                        nPartial * 8);',
    '                    WholeReduceMax(',
    '                        reduceWork,',
    '                        cUb,',
    '                        64,',
    '                        static_cast<int32_t>(',
    '                            nPartial),',
    '                        8,',
    '                        1,',
    '                        8,',
    '                        ReduceOrder::ORDER_ONLY_VALUE);',
    '                    WholeReduceMax(',
    '                        tileMaxVec,',
    '                        reduceWork,',
    '                        static_cast<int32_t>(',
    '                            wRow * 8),',
    '                        static_cast<int32_t>(validM),',
    '                        1,',
    '                        1,',
    '                        static_cast<int32_t>(wRow),',
    '                        ReduceOrder::ORDER_ONLY_VALUE);',
    '                } else if (validN <= 64) {',
    '                    WholeReduceMax(',
    '                        tileMaxVec,',
    '                        cUb,',
    '                        static_cast<int32_t>(validN),',
    '                        static_cast<int32_t>(validM),',
    '                        1,',
    '                        1,',
    '                        static_cast<int32_t>(',
    '                            rowPitch / 8),',
    '                        ReduceOrder::ORDER_ONLY_VALUE);',
    '                } else {',
    '                    for (uint32_t r = 0; r < validM;',
    '                         ++r) {',
    '                        ReduceMax(',
    '                            tileMaxVec[r],',
    '                            cUb[r * rowPitch],',
    '                            reduceWork,',
    '                            static_cast<int32_t>(',
    '                                validN),',
    '                            false);',
    '                    }',
    '                }',
    '',
    '                Max(',
    '                    bestVec,',
    '                    bestVec,',
    '                    tileMaxVec,',
    '                    validM);',
    '',
    '                /*',
    '                 * WholeReduceMax is a bare vcmax with',
    '                 * no internal pipe sync (unlike',
    '                 * ReduceMax\'s V_S/S_MTE3 drains), so',
    '                 * the next chunk\'s DataCopy into cUb',
    '                 * needs an explicit WAR gate.',
    '                 */',
    '                Fence<HardEvent::V_MTE2>(pipe);',
    '            }',
    '',
    '            const uint64_t pOff =',
    '                (',
    '                    static_cast<uint64_t>(batch) * rowTiles +',
    '                    mwin',
    '                ) * nChunksTask + chunk;',
    '',
    '            DataCopyExtParams ocp;',
    '            ocp.blockCount = 1;',
    '            ocp.blockLen = validM * sizeof(float);',
    '            ocp.srcStride = 0;',
    '            ocp.dstStride = 0;',
    '            ocp.rsv = 0;',
    '            Fence<HardEvent::V_MTE3>(pipe);',
    '            DataCopyPad(',
    '                partialGm[pOff * TILE_M + msub * subM],',
    '                bestVec,',
    '                ocp);',
    '',
    '            Fence<HardEvent::MTE3_S>(pipe);']),
    J([
    '                /*',
    '                 * Reduce one 16-row sub-window at a time. subM2 equals validM',
    '                 * when the task is a single sub-window (the earlier shape).',
    '                 */',
    '                for (uint32_t w2 = 0; w2 < subWins; ++w2) {',
    '                const uint32_t w2Off = w2 * TILE_M * rowPitch;',
    '                const uint32_t subM2 = MinU32(',
    '                    validM, shape.m - (rowStart + w2 * TILE_M));',
    '                Duplicate(',
    '                    tileMaxVec,',
    '                    -3.402823466e38f,',
    '                    TILE_M);',
    '',
    '                if (rowPitch == validN) {',
    '                    /*',
    '                     * Contiguous rows: one vcmax pass',
    '                     * over subM2*wRow windows (mask=64)',
    '                     * lands partials on an 8-elem pitch',
    '                     * (dstRepStride=8); gaps pre-filled',
    '                     * with -inf so a second pass can',
    '                     * fold each row\'s wRow*8-elem group',
    '                     * contiguously. wRow<=8 keeps both',
    '                     * masks under the 64-elem limit.',
    '                     */',
    '                    const uint32_t wRow = validN >> 6;',
    '                    const uint32_t nPartial =',
    '                        subM2 * wRow;',
    '                    Duplicate(',
    '                        reduceWork,',
    '                        -3.402823466e38f,',
    '                        nPartial * 8);',
    '                    WholeReduceMax(',
    '                        reduceWork,',
    '                        cUb[w2Off],',
    '                        64,',
    '                        static_cast<int32_t>(',
    '                            nPartial),',
    '                        8,',
    '                        1,',
    '                        8,',
    '                        ReduceOrder::ORDER_ONLY_VALUE);',
    '                    WholeReduceMax(',
    '                        tileMaxVec,',
    '                        reduceWork,',
    '                        static_cast<int32_t>(',
    '                            wRow * 8),',
    '                        static_cast<int32_t>(subM2),',
    '                        1,',
    '                        1,',
    '                        static_cast<int32_t>(wRow),',
    '                        ReduceOrder::ORDER_ONLY_VALUE);',
    '                } else if (validN <= 64) {',
    '                    WholeReduceMax(',
    '                        tileMaxVec,',
    '                        cUb[w2Off],',
    '                        static_cast<int32_t>(validN),',
    '                        static_cast<int32_t>(subM2),',
    '                        1,',
    '                        1,',
    '                        static_cast<int32_t>(',
    '                            rowPitch / 8),',
    '                        ReduceOrder::ORDER_ONLY_VALUE);',
    '                } else {',
    '                    for (uint32_t r = 0; r < subM2;',
    '                         ++r) {',
    '                        ReduceMax(',
    '                            tileMaxVec[r],',
    '                            cUb[w2Off + r * rowPitch],',
    '                            reduceWork,',
    '                            static_cast<int32_t>(',
    '                                validN),',
    '                            false);',
    '                    }',
    '                }',
    '',
    '                Max(',
    '                    bestVec[w2 * TILE_M],',
    '                    bestVec[w2 * TILE_M],',
    '                    tileMaxVec,',
    '                    subM2);',
    '                }',
    '',
    '                /*',
    '                 * WholeReduceMax is a bare vcmax with',
    '                 * no internal pipe sync (unlike',
    '                 * ReduceMax\'s V_S/S_MTE3 drains), so',
    '                 * the next chunk\'s DataCopy into cUb',
    '                 * needs an explicit WAR gate.',
    '                 */',
    '                Fence<HardEvent::V_MTE2>(pipe);',
    '            }',
    '',
    '            for (uint32_t w2 = 0; w2 < subWins; ++w2) {',
    '            const uint32_t subM2 = MinU32(',
    '                validM, shape.m - (rowStart + w2 * TILE_M));',
    '            const uint64_t pOff =',
    '                (',
    '                    static_cast<uint64_t>(batch) * rowTiles +',
    '                    (mwin * (aivRows / TILE_M) + w2)',
    '                ) * nChunksTask + chunk;',
    '',
    '            DataCopyExtParams ocp;',
    '            ocp.blockCount = 1;',
    '            ocp.blockLen = subM2 * sizeof(float);',
    '            ocp.srcStride = 0;',
    '            ocp.dstStride = 0;',
    '            ocp.rsv = 0;',
    '            Fence<HardEvent::V_MTE3>(pipe);',
    '            DataCopyPad(',
    '                partialGm[pOff * TILE_M + msub * subM],',
    '                bestVec[w2 * TILE_M],',
    '                ocp);',
    '',
    '            Fence<HardEvent::MTE3_S>(pipe);',
    '            }']))

open(DST, 'w', encoding='utf-8', newline='').write(raw.replace('\n', '\r\n'))
print('wrote %s: %d lines (was %d)' % (DST, len(raw.split('\n')), N))
